### ISSUE TITLE
Elementary OS 5: cannot install

### ISSUE THREAD

**Issue by HerrAugust** [phw/peek#400]
sudo add-apt-repository ppa:peek-developers/stable

Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 107, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 128, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 623, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for elementary/juno

**Comment by TBera9** [comment]
could you solve it? I'm with a similar problem

**Comment by luzpaz** [comment]
@HerrAugust @TBera9 this may be an upstream issue.

**Comment by phw** [comment]
I don't know how Ubuntu PPAs are supported by Elementary, but I don't support packaging for Elementary myself.
